In [3]:
import numpy as np

a = np.random.randn(5)
print(a)
print(a.shape)


[ 0.44041513  1.31339621 -0.7955573   1.16193946  0.26734949]
(5,)


In [4]:
print(a.T)

[ 0.44041513  1.31339621 -0.7955573   1.16193946  0.26734949]


In [5]:
print(np.dot(a, a.T))

3.973465564859475


In [7]:
a = np.random.randn(5,1)
print(a)

[[-0.81591394]
 [-1.51177177]
 [ 0.22177132]
 [-0.48497462]
 [-1.24865196]]


In [10]:
print(a.T)
print(a.T.shape)

[[-0.81591394 -1.51177177  0.22177132 -0.48497462 -1.24865196]]
(1, 5)


In [43]:
a = np.array([[1,1,1],[2,2,2],[3,3,3]])
b = np.array([[10],[10],[10]])
print(a*b)

a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

print(c.shape)
print(c)

[[10 10 10]
 [20 20 20]
 [30 30 30]]
(3, 3)
[[-0.81916695 -0.31421847  0.93607107]
 [-0.30197191 -0.57940827  0.26516616]
 [ 1.21963621  1.71125415 -2.09406589]]


In [25]:
print(np.dot(a,a.T))

[[ 4.36406284  0.57920459 -1.30960272]
 [ 0.57920459  4.5925048  -1.03695723]
 [-1.30960272 -1.03695723  0.69540122]]
